name: Generate meta info

on: [ push, pull_request, pull_request_target ]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run generator
      run: python3.9 ${{ github.workspace }}/scripts/cmake_generate.py

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: apply formatting
